http://d2l.ai/chapter_preliminaries/ndarray.html

In [1]:
%%time
import torch

Wall time: 853 ms


In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

shape (the length along each axis)
the total number of elements in an ndarray

In [3]:
x.shape

torch.Size([12])

In [4]:
x.size()

torch.Size([12])

In [5]:
x = x.reshape((3, 4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

We invoke this capability by placing -1 for the dimension that we would like ndarray to automatically infer. In our case, instead of calling x.reshape(3, 4), we could have equivalently called x.reshape(-1, 4) or x.reshape(3, -1).

In [6]:
x = x.reshape((3, -1))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
x = x.reshape((-1,4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

The empty method grabs a chunk of memory and hands us back a matrix without bothering to change the value of any of its entries. This is remarkably efficient but we must be careful because the entries might take arbitrary values, including very big ones!

In [8]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

input = torch.empty(2, 3)
torch.zeros_like(input)

We can create an ndarray representing a tensor with all elements set to 0 and a shape of (2, 3, 4) as follows:
Similarly, we can create tensors with each element set to 1 as follows:

In [9]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1.

In [11]:
torch.randn(3, 4)

tensor([[ 0.8159,  0.5000,  0.6834,  0.4439],
        [-0.1392, -1.4270,  0.3516,  1.1271],
        [ 2.2247,  0.1028,  0.4762, -1.1010]])

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])