In [1]:
import torch

In [2]:
from torch.autograd import Variable

In [3]:
x = torch.arange(4.0, requires_grad=True)
# make it as a Variable with a gradient taken.
x =  torch.autograd.Variable(x, requires_grad=True)
y = x * x
y.backward(torch.ones(y.size()))

framework: https://zh.mxnet.io/blog/learn-mxnet-for-pytorch-users
torch.autograd.Variable(x, requires_grad=True)：https://www.codetd.com/article/6409254
y.backward(torch.ones(y.size()))：https://www.cnblogs.com/wanghui-garcia/p/10629227.html
autograd_api: https://pytorch.org/docs/stable/autograd.html

In [4]:
u = x.detach()

In [5]:
u = torch.autograd.Variable(u, requires_grad=True)

In [6]:
v = u * u

In [7]:
v.backward(torch.ones(v.size()))

In [8]:
x.grad

tensor([0., 2., 4., 6.])

In [9]:
u.grad

tensor([0., 2., 4., 6.])

In [10]:
x.grad == u.grad

tensor([True, True, True, True])