### Differentiation is a crucial step

But for complex models, the calculation of differentiation by hand can be a pain (and often error-prone).

So we need to automatic it!

In [1]:
import torch

In [2]:
# require a place to store the gradient of  y  with respect to  x. 
x = torch.arange(4.0, requires_grad=True) # it tells the framework we need allocate gradient space for x in the future.
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
x.grad

In [4]:
y = 2 * torch.dot(x, x)
y 
# 1 + 2**2 + 3**2 = 14,then 14*2 = 28

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()

The gradient of the function  y=2x⊤x  with respect to  x  should be  4x .
[0, 1. * 4, 2.* 4, 3.* 4]==[ 0.,  4.,  8., 12.]

In [6]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad.zero_() #  clear the previous values in x.grad first
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

1 + 2 + 3 == 6
x' == 1


In [8]:
y

tensor(6., grad_fn=<SumBackward0>)

In [9]:
with autograd.record():
    y = x * x  # `y` is a vector
y.backward()

u = x.copy()
u.attach_grad()
with autograd.record():
    v = (u * u).sum()  # `v` is a scalar
v.backward()

x.grad == u.grad

NameError: name 'autograd' is not defined

In [10]:
import torch.autograd

In [11]:
with autograd.record():
    y = x * x  # `y` is a vector
y.backward()

u = x.copy()
u.attach_grad()
with autograd.record():
    v = (u * u).sum()  # `v` is a scalar
v.backward()

x.grad == u.grad

NameError: name 'autograd' is not defined

backward:https://zhuanlan.zhihu.com/p/97045053

https://www.quora.com/What-is-the-difference-between-a-Tensor-and-a-Variable-in-Pytorch

only MXnet

https://pytorch.org/docs/stable/autograd.html
https://pytorch-cn.readthedocs.io/zh/latest/package_references/torch-autograd/


In [12]:

from torch.autograd import Variable

In [ ]:
x = V(t.Tensor([4]), requires_grad=True)
y = x ** 2 
 
grad_x = t.autograd.grad(y, x, create_graph=True)
print(grad_x)  # dy/dx = 2*x = 8
 
grad_2x = t.autograd.grad(grad_x[0],x)
print(grad_2x) # d(2*x)/dx = 2