In [1]:
import torch

In [2]:
x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
x.grad

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()

In [6]:
y.backward()

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [7]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward(retain_graph=True)

In [9]:
y.backward(retain_graph=True)

In [10]:
a = torch.randn(20).reshape(5, 4)

In [11]:
def f(a):
    b = a * 2
    while b.norm().item() < 1000:
        b = b * 2
    if b.sum().item() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [13]:
a = torch.randn(size = (5, 4) requires_grad=True )

SyntaxError: invalid syntax (<ipython-input-13-f11fef37280f>, line 1)

In [15]:
a = torch.randn(20, requires_grad=True).reshape(5, 4)

In [16]:
a

tensor([[-1.5373,  1.2475, -1.1517, -0.1640],
        [ 1.8807, -1.1592,  0.7172, -0.7673],
        [-1.4704, -0.0927,  0.4405,  0.7891],
        [ 0.0064,  0.1158, -0.3097, -0.7860],
        [-0.0778, -1.2482,  1.3036,  0.3225]], grad_fn=<ViewBackward>)

In [17]:
d = f(a)
d

tensor([[-39353.7305,  31935.8613, -29482.5410,  -4197.6743],
        [ 48145.5430, -29675.6621,  18360.6875, -19642.9688],
        [-37643.1992,  -2372.4202,  11276.8711,  20199.9492],
        [   165.0550,   2963.2859,  -7927.3711, -20122.3086],
        [ -1992.2642, -31955.1602,  33371.5117,   8254.8330]],
       grad_fn=<MulBackward0>)

In [18]:
d.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [19]:
from 2-4 import plot

SyntaxError: invalid syntax (<ipython-input-19-bea5b31724ad>, line 1)

In [20]:
from ./2-4 import plot

SyntaxError: invalid syntax (<ipython-input-20-4ae31ddd1ab0>, line 1)

In [21]:
from .2-4 import plot

SyntaxError: invalid syntax (<ipython-input-21-3b8183fcef3b>, line 1)

数字改为字母！

In [22]:
from .two_four import plot

ImportError: attempted relative import with no known parent package

In [23]:
from d2l import torch as d2l
from IPython import display
import numpy as np
from .two_four import plot

ModuleNotFoundError: No module named 'd2l'

In [24]:
from ..d2l import torch as d2l
from IPython import display
import numpy as np
from .two_four import plot

ImportError: attempted relative import with no known parent package

In [25]:
%matplotlib inline
from ..d2l import torch as d2l
from IPython import display
import numpy as np
from .two_four import plot

ImportError: attempted relative import with no known parent package