In [1]:
import torch

In [2]:
x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
x.grad

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()

In [6]:
y.backward()

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [7]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward(retain_graph=True)

In [9]:
y.backward(retain_graph=True)

In [10]:
a = torch.randn(20).reshape(5, 4)

In [11]:
def f(a):
    b = a * 2
    while b.norm().item() < 1000:
        b = b * 2
    if b.sum().item() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [12]:
a = torch.randn(size = (5, 4) requires_grad=True )

SyntaxError: invalid syntax (<ipython-input-12-f11fef37280f>, line 1)

In [13]:
a = torch.randn(20, requires_grad=True).reshape(5, 4)

In [14]:
a

tensor([[ 0.8719,  1.2118, -0.8325,  1.6660],
        [-1.2418,  0.2467, -0.2110,  1.5497],
        [ 1.4217,  1.1514,  0.8179,  1.2958],
        [-1.9090,  0.5285, -0.4018,  0.4226],
        [-1.1192, -0.2078, -2.0724, -1.3385]], grad_fn=<ViewBackward>)

In [15]:
d = f(a)
d

tensor([[ 223.2136,  310.2283, -213.1152,  426.4952],
        [-317.9097,   63.1571,  -54.0234,  396.7339],
        [ 363.9469,  294.7630,  209.3711,  331.7216],
        [-488.6983,  135.2873, -102.8704,  108.1836],
        [-286.5133,  -53.2001, -530.5232, -342.6625]], grad_fn=<MulBackward0>)

In [16]:
d.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [17]:
from 2-4 import plot

SyntaxError: invalid syntax (<ipython-input-17-bea5b31724ad>, line 1)

In [18]:
from ./2-4 import plot

SyntaxError: invalid syntax (<ipython-input-18-4ae31ddd1ab0>, line 1)

In [19]:
from .2-4 import plot

SyntaxError: invalid syntax (<ipython-input-19-3b8183fcef3b>, line 1)

数字改为字母！

In [20]:
from .two_four import plot

ImportError: attempted relative import with no known parent package

In [21]:
from d2l import torch as d2l
from IPython import display
import numpy as np
from .two_four import plot

ImportError: attempted relative import with no known parent package

In [22]:
from ..d2l import torch as d2l
from IPython import display
import numpy as np
from .two_four import plot

ImportError: attempted relative import with no known parent package

In [23]:
%matplotlib inline
from ..d2l import torch as d2l
from IPython import display
import numpy as np
from .two_four import plot

ImportError: attempted relative import with no known parent package

In [24]:
b = torch.randn(size=(1,), requires_grad=True)
b = b + 1000

In [25]:
b

tensor([1000.8587], grad_fn=<AddBackward0>)

In [26]:
d = f(b)
d
d.backward()

In [27]:
d / b

tensor([2.], grad_fn=<DivBackward0>)

In [28]:
b.grad

In [29]:
print(b.grad)

None
