In [1]:
import torch


In [2]:
# require a place to store the gradient of  y  with respect to  x. 
x = torch.arange(4.0, requires_grad=True) # it tells the framework we need allocate gradient space for x in the future.
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
x.grad


In [4]:
y = 2 * torch.dot(x, x)
y 
# 1 + 2**2 + 3**2 = 14,then 14*2 = 28

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()

In [6]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [8]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [10]:
def f(a):
    b = a * 2
    while b.norm().item() < 1000:#return the number that is in tensor()'s brackets.
        b = b * 2
    if b.sum().item() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [11]:
a.grad == (d / a)

NameError: name 'a' is not defined

In [12]:
a = torch.randn(size=(1,), requires_grad=True)
# record the calculation
d = f(a)
d.backward()

In [13]:
a.grad == (d / a)

tensor([True])

In [14]:
b = torch.randn(size=(1,), requires_grad=True)
b = b + 1000
# record the calculation
d = f(b)
d.backward()
b.grad == (d / b)

False

In [15]:
b = torch.randn(size=(1,), requires_grad=True)
b = b + 1000
# record the calculation
d = f(b)
d.backward()

In [17]:
d

tensor([1999.6416], grad_fn=<MulBackward0>)

In [18]:
b

tensor([999.8208], grad_fn=<AddBackward0>)

In [21]:
t = b.grad
t

In [16]:
b.grad == (d / b)

False