### Differentiation is a crucial step

But for complex models, the calculation of differentiation by hand can be a pain (and often error-prone).

So we need to automatic it!

In [1]:
import torch

In [2]:
# require a place to store the gradient of  y  with respect to  x. 
x = torch.arange(4.0, requires_grad=True) # it tells the framework we need allocate gradient space for x in the future.
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
x.grad

In [4]:
y = 2 * torch.dot(x, x)
y 
# 1 + 2**2 + 3**2 = 14,then 14*2 = 28

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()

The gradient of the function  y=2x⊤x  with respect to  x  should be  4x .
[0, 1. * 4, 2.* 4, 3.* 4]==[ 0.,  4.,  8., 12.]

In [6]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad.zero_() #  clear the previous values in x.grad first
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

1 + 2 + 3 == 6

x[x1, x2, x3, x4] = [0., 1., 2., 3.]

y = x.sum() is equal to y = x1+x2+x3+x4

Then partial derivative:

p(y)/p(x1) = p(y)/p(x2) = p(y)/p(x3) =p(y)/p(x4) = 1 
（The coefficients of the linear equation)




In [8]:
y

tensor(6., grad_fn=<SumBackward0>)

In [9]:
with autograd.record():
    y = x * x  # `y` is a vector
y.backward()

u = x.copy()
u.attach_grad()
with autograd.record():
    v = (u * u).sum()  # `v` is a scalar
v.backward()

x.grad == u.grad

NameError: name 'autograd' is not defined

In [10]:
import torch.autograd

In [11]:
with autograd.record():
    y = x * x  # `y` is a vector
y.backward()

u = x.copy()
u.attach_grad()
with autograd.record():
    v = (u * u).sum()  # `v` is a scalar
v.backward()

x.grad == u.grad

NameError: name 'autograd' is not defined

backward:https://zhuanlan.zhihu.com/p/97045053

https://www.quora.com/What-is-the-difference-between-a-Tensor-and-a-Variable-in-Pytorch

only MXnet

https://pytorch.org/docs/stable/autograd.html
https://pytorch-cn.readthedocs.io/zh/latest/package_references/torch-autograd/


In [12]:

from torch.autograd import Variable

In [ ]:
x = V(t.Tensor([4]), requires_grad=True)
y = x ** 2 
 
grad_x = t.autograd.grad(y, x, create_graph=True)
print(grad_x)  # dy/dx = 2*x = 8
 
grad_2x = t.autograd.grad(grad_x[0],x)
print(grad_2x) # d(2*x)/dx = 2

In [13]:
xv =  torch.autograd.Variable(x)
y = xv * xv
y.backward()


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [14]:
x = torch.arange(4.0, requires_grad=True)
xv =  torch.autograd.Variable(x)
y = xv * xv
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [15]:
x = torch.arange(4.0, requires_grad=True)
xv =  torch.autograd.Variable(x, requires_grad=True)
y = xv * xv
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [16]:
x = torch.arange(4.0, requires_grad=True)
xv =  torch.autograd.Variable(x, requires_grad=True)
y = xv * xv
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [17]:
x = torch.arange(4.0, requires_grad=True)
xv =  torch.autograd.Variable(x)
y = xv * xv
y.backward(y.ones(y.size()))

AttributeError: 'Tensor' object has no attribute 'ones'

In [18]:
x = torch.arange(4.0, requires_grad=True)
xv =  torch.autograd.Variable(x)
y = xv * xv

In [19]:
y

tensor([0., 1., 4., 9.])

In [20]:
y.backward(y.ones(y.size()))

AttributeError: 'Tensor' object has no attribute 'ones'

In [21]:
y.backward(t.ones(y.size()))

NameError: name 't' is not defined

In [22]:
y.backward(torch.ones(y.size()))


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [23]:
x = torch.arange(4.0, requires_grad=True)
xv =  torch.autograd.Variable(x, requires_grad=True)
y = xv * xv
y.backward(torch.ones(y.size()))


framework: https://zh.mxnet.io/blog/learn-mxnet-for-pytorch-users
torch.autograd.Variable(x, requires_grad=True)：https://www.codetd.com/article/6409254
y.backward(torch.ones(y.size()))：https://www.cnblogs.com/wanghui-garcia/p/10629227.html
autograd_api: https://pytorch.org/docs/stable/autograd.html

In [49]:
x = torch.arange(4.0, requires_grad=True)
xv =  torch.autograd.Variable(x, requires_grad=True)
y = xv * xv
y
y.backward(torch.ones(y.size()))

In [50]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [24]:
uv = xv.copy()

AttributeError: 'Tensor' object has no attribute 'copy'

https://blog.csdn.net/winycg/article/details/100813519

In [37]:
uv = xv.clone()

In [ ]:
uv = Variable(torch.FloatTensor(1), requires_grad=True)


In [38]:
y = (uv * uv).sum()

In [39]:
y.backward(torch.ones(y.size()))

In [40]:
xv.grad == uv.grad


False

In [30]:
y = (xv * xv).sum()

In [31]:
y.backward(torch.ones(y.size()))

In [32]:
xv.grad == uv.grad
# clone()函数可以返回一个完全相同的tensor,新的tensor开辟新的内存，但是仍然留在计算图中。

False

In [41]:
wv = xv.detach()



In [51]:
wv

tensor([0., 1., 2., 3.])

In [55]:
wv =torch.autograd.Variable(wv, requires_grad=True)

In [56]:
y = xv * xv

In [57]:
y.backward(torch.ones(y.size()))

In [58]:
xv.grad == wv.grad

False

In [44]:
wv = xv.detach(requires_grad=True)

TypeError: detach() takes no keyword arguments

In [54]:
wv = wv.(requires_grad=True)

SyntaxError: invalid syntax (<ipython-input-54-10b104092f1e>, line 1)

In [ ]:
wv = 

In [42]:
y = wv * wv

In [52]:
y = wv * wv
y

tensor([0., 1., 4., 9.])

In [53]:
y.backward(torch.ones(y.size()))

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [47]:
y = (wv * wv).sum()
y

tensor(14.)

In [48]:
y.backward(torch.ones(y.size()))

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [46]:
y.backward(torch.ones(y.size()))

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [43]:
y.backward(torch.ones(y.size()))

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [26]:
# u = x.copy()
uv.attach_grad()
y = xv * xv
y.backward(torch.ones(y.size()))

AttributeError: 'Tensor' object has no attribute 'attach_grad'

In [1]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

NameError: name 'x' is not defined