In [1]:
%matplotlib inline
from mxnet import np, npx

In [2]:
np.random.multinomial(10, fair_probs)


NameError: name 'fair_probs' is not defined

In [3]:
%matplotlib inline
from d2l import mxnet as d2l
from mxnet import np, npx
import random
npx.set_np()

In [4]:
fair_probs = [1.0 / 6] * 6
np.random.multinomial(1, fair_probs)

array([0, 0, 0, 0, 0, 1], dtype=int64)

In [5]:
np.random.multinomial(10, fair_probs)

array([ 0,  0,  0,  0,  0, 10], dtype=int64)

In [6]:
np.random.multinomial(10, fair_probs)

array([ 0,  0,  0,  0,  0, 10], dtype=int64)

In [7]:
np.random.multinomial(10, fair_probs)

array([ 0,  0,  0,  0,  0, 10], dtype=int64)