In [1]:
import torch
print(dir(torch.distributions))

['AbsTransform', 'AffineTransform', 'Bernoulli', 'Beta', 'Binomial', 'CatTransform', 'Categorical', 'Cauchy', 'Chi2', 'ComposeTransform', 'ContinuousBernoulli', 'Dirichlet', 'Distribution', 'ExpTransform', 'Exponential', 'ExponentialFamily', 'FisherSnedecor', 'Gamma', 'Geometric', 'Gumbel', 'HalfCauchy', 'HalfNormal', 'Independent', 'Laplace', 'LogNormal', 'LogisticNormal', 'LowRankMultivariateNormal', 'LowerCholeskyTransform', 'MixtureSameFamily', 'Multinomial', 'MultivariateNormal', 'NegativeBinomial', 'Normal', 'OneHotCategorical', 'Pareto', 'Poisson', 'PowerTransform', 'RelaxedBernoulli', 'RelaxedOneHotCategorical', 'SigmoidTransform', 'SoftmaxTransform', 'StackTransform', 'StickBreakingTransform', 'StudentT', 'TanhTransform', 'Transform', 'TransformedDistribution', 'Uniform', 'VonMises', 'Weibull', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'bernoulli', 'beta', 'biject_to', 'binomial', 'categoric

Generally, we can ignore functions that start and end with __ (special objects in Python) or functions that start with a single _(usually internal functions).

In [2]:
help(torch.ones_like)

Help on built-in function ones_like:

ones_like(...)
    ones_like(input, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor
    
    Returns a tensor filled with the scalar value `1`, with the same size as
    :attr:`input`. ``torch.ones_like(input)`` is equivalent to
    ``torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.
    
    .. warning::
        As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
        the old ``torch.ones_like(input, out=output)`` is equivalent to
        ``torch.ones(input.size(), out=output)``.
    
    Args:
        input (Tensor): the size of :attr:`input` will determine size of the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
            Default: if ``None``, defaults to the dtype of :attr:`input`.
        layout (:class:`torch.layout`, optional): the desired layout of 

In [3]:
x = torch.tensor([[0., 0., 0.], [2., 2., 2.]])
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
np.random.choice(4, 2)

NameError: name 'np' is not defined

In [5]:
import numpy as np

In [6]:
np.random.choice(4, 2)

array([0, 1])

In [7]:
np.random.choice(4, 2)

array([0, 1])

In [8]:
np.random.choice(4, 2)

array([3, 0])

https://blog.csdn.net/ImwaterP/article/details/96282230

In [10]:
def my_random_choice(int x, size = int y):
    my_list = []
    while y > 0:
        mylist.append(np.random.randint(0, x))
        y -= 1
    return np.array(my_list)

SyntaxError: invalid syntax (<ipython-input-10-822edf7d4bd3>, line 1)

In [11]:
def my_random_choice(x, size = int y):
    my_list = []
    while y > 0:
        mylist.append(np.random.randint(0, x))
        y -= 1
    return np.array(my_list)

SyntaxError: invalid syntax (<ipython-input-11-ed5d453a9882>, line 1)

In [12]:
def my_random_choice(x, size = int y):
    my_list = []
    while y > 0:
        mylist.append(np.random.randint(0, x))
        y -= 1
    return np.array(my_list)

SyntaxError: invalid syntax (<ipython-input-12-ed5d453a9882>, line 1)

In [13]:
def my_random_choice(x, size = y):
    my_list = []
    while y > 0:
        mylist.append(np.random.randint(0, x))
        y -= 1
    return np.array(my_list)

NameError: name 'y' is not defined

In [14]:
def my_random_choice(x, y):
    my_list = []
    while y > 0:
        mylist.append(np.random.randint(0, x))
        y -= 1
    return np.array(my_list)

In [15]:
my_random_choice(4, 2)

NameError: name 'mylist' is not defined

In [18]:
def my_random_choice(x, y):
    my_list = []
    while y > 0:
        my_list.append(np.random.randint(0, x))
        y -= 1
    return np.array(my_list)

In [19]:
my_random_choice(4, 2)

array([2, 0])